### ISSUE TITLE
Unable to get working on windows

### ISSUE THREAD

**Issue by blake-newman** [garetht/retina-brunch#4]
I am unable to get this working on windows

Error message i receive is: 
retina-brunch couldn't get file info of `public\images\menu\logo@2x.jpg`. Error: `Error: Command failed: The system cannot find the path specified. : The system cannot find the path specified.`

**Comment by sams** [comment]
I have been using brunch on windows for the last few weeks. this bugbear issue you report is alike my issue with uncss. I bet this all smooths out on no windoze. I am/was hoping to be able to debug the paths being attempted. Any ideas to find the underlying kookiness to such bugbears?

**Comment by blake-newman** [comment]
I believe its to do with the way the path is formatted. Maybe its using forward slashes when windows needs back slashes. When I get time I may investigate further.

**Comment by sams** [comment]
netbpm is a pain. Current unable to get windoze 7 to be able to find jpegtopmn.

part of my issue might be that I am installing a newer version of netbpm (specifically gnuwin32 latest - I have read that pnmscale is out of date pamscale replaces it). Anyway it appears something is messing my node/npm install and access to modules is lost on occasion.

I think the stumbling point it something to do with my install of netbpm and all might be fine if I can resolve that
